title: Prototyping Macines
baseurl: "/prototyping-machines" # the subpath of your site, e.g. /blog
url: "https://interface.fh-potsdam.de" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  smart_quotes:   lsquo,rsquo,ldquo,rdquo

sass:
  sass_dir: assets/_scss
  style: compressed
